nurse/urls.py
from django.conf.urls import url, include
from rest_framework import routers
from . import api
from . import views

router = routers.DefaultRouter()
router.register(r'nurse', api.modelsViewSet)


urlpatterns = (
    # urls for Django Rest Framework API
    url(r'^api/v1/', include(router.urls)),
)

urlpatterns += (
    # urls for models
    # url(r'^nurse/list/$', views.ModelsListView.as_view(), name='nurse_triage_list'),
    url(r'^nurse/', views.NurseLandingView.as_view(), name='nurse_landing'),
    url(r'^create/(?P<patient_no>\S+)/$', views.NurseCreateView.as_view(), name='nurse_triage_create'),
    url(r'^nurse/detail/(?P<slug>\S+)/$', views.NurseDetailView.as_view(), name='nurse_triage_detail'),
    url(r'^nurse/update/(?P<slug>\S+)/$', views.NurseUpdateView.as_view(), name='nurse_triage_update'),
)

valentisHealth/urls.py
from django.conf.urls import url, include
from django.contrib import admin
from account.views import Home
from django.conf import settings
from django.conf.urls.static import static

admin.site.site_header = 'ValentisHealth Administration'
admin.site.site_title = 'ValentisHealth Administration'

urlpatterns = [
                  url(r'^tunnel/', admin.site.urls),
                  url(r'^registration/', include('registration.urls')),
                  url(r'^nurse/', include('nurse.urls')),
                  url(r'^medication/', include('medication.urls')),
                  url(r'^billing/', include('billing.urls')),
                  url(r'^tests/', include('tests.urls')),
                  url(r'^cashier/', include('cashier.urls')),
                  url(r'^clinic/', include('clinic.urls')),
                  url(r'^payments/', include('payments.urls')),
                  url(r'^account/', include('account.urls')),
                  url(r'^workflow/', include('workflow.urls')),
                  url(r'^$', include('registration.urls')),
              ] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

clinic/models.py
from django.core.urlresolvers import reverse
from django_extensions.db.fields import AutoSlugField
from django.db.models import *
from django.conf import settings
from django.contrib.contenttypes.fields import GenericForeignKey
from django.contrib.contenttypes.models import ContentType
from django.contrib.auth import get_user_model
from django.contrib.auth import models as auth_models
from django.db import models as models
from django_extensions.db import fields as extension_fields
import uuid

class PatientVisit(models.Model):

    # Fields
    name = models.CharField(max_length=255, null=True, blank=True)
    slug = extension_fields.AutoSlugField(populate_from='patient_no', blank=True)
    created = models.DateTimeField(auto_now_add=True, editable=False)
    last_updated = models.DateTimeField(auto_now=True, editable=False)
    patient_no = models.CharField(max_length=30, null=True, blank=True)
    visit_id = models.UUIDField(primary_key=True, default=uuid.uuid4, editable=False)
    radiology_no = models.CharField(max_length=255, null=True, blank=True)
    triage_id = models.CharField(max_length=255, null=True, blank=True)
    notes = models.TextField(max_length=200, null=True, blank=True)
    diagnosis = models.TextField(max_length=100, null=True, blank=True)
    prescription_id = models.CharField(max_length=255, null=True, blank=True)
    status = models.CharField(max_length=30, null=True, blank=True)
    examination = models.CharField(max_length=255, null=True, blank=True)
    plan_of_managemnt = models.CharField(max_length=255, null=True, blank=True)
    query_diagnosis = models.CharField(max_length=255, null=True, blank=True)
    his_presenting_illness = models.CharField(max_length=255, null=True, blank=True)
    attending_doctor = models.CharField(max_length=255, null=True, blank=True)
    diag_search = models.CharField(max_length=255, null=True, blank=True)
    current_diagnosis = models.CharField(max_length=255, null=True, blank=True)



    class Meta:
        ordering = ('last_updated',)

    def __unicode__(self):
        return u'%s' % self.slug

    def get_absolute_url(self):
        return reverse('clinic_patientvisit_detail', args=(self.slug,))


    def get_update_url(self):
        return reverse('clinic_patientvisit_update', args=(self.slug,))

class Diagnosis(models.Model):

    # Fields
    created = models.DateTimeField(auto_now_add=True, editable=False)
    last_updated = models.DateTimeField(auto_now=True, editable=False)
    code = models.CharField(max_length=255)
    name = models.CharField(max_length=500)

class Radiologylist(models.Model):
    group = models.CharField(max_length=255,blank=True)
    modality = models.CharField(max_length=255,blank=True)
    tests = models.CharField(max_length=300,blank=True)
class RadiologyTestsresults(models.Model):
    radiologytestid = models.CharField(max_length=255,blank=True)
    status = models.CharField(max_length=255,blank=True)
    resulturl = models.CharField(max_length=255,blank=True)
    uploaded_on= models.DateTimeField(auto_now=True, editable=False)

class LabTestsresults(models.Model):
    labtestid = models.CharField(max_length=255,blank=True)
    status = models.CharField(max_length=255,blank=True)
    resulturl = models.CharField(max_length=255,blank=True)
    uploaded_on= models.DateTimeField(auto_now=True, editable=False)

nurse/models.py
from django.core.urlresolvers import reverse
from django_extensions.db.fields import AutoSlugField
from django.db.models import *
from django.conf import settings
from django.contrib.contenttypes.fields import GenericForeignKey
from django.contrib.contenttypes.models import ContentType
from django.contrib.auth import get_user_model
from django.contrib.auth import models as auth_models
from django.db import models as models
from django_extensions.db import fields as extension_fields
import uuid
from registration.models import Patient

class Nurse(models.Model):

    # Fields
    slug = extension_fields.AutoSlugField(populate_from='patient_no',null=True, blank=True)
    created = models.DateTimeField(auto_now_add=True, editable=False)
    last_updated = models.DateTimeField(auto_now=True, editable=False)
    triage_id = models.UUIDField(primary_key=True, default=uuid.uuid4, editable=False)
    systolic = models.IntegerField()
    diastolic = models.IntegerField()
    temperature = models.FloatField()
    oxygen_saturation = models.FloatField()
    urinalysis = models.TextField(max_length=400, null=True, blank=True)
    random_glucose = models.TextField(max_length=400, null=True, blank=True)
    heart_rate = models.CharField(max_length=100)
    weight = models.CharField(max_length=100)
    height = models.CharField(max_length=100)
    others = models.TextField(max_length=200, null=True, blank=True)
    attending_nurse = models.CharField(max_length=255, null=True, blank=True)
    patient_no = models.CharField(max_length=30, null=True, blank=True)
    patient_data = models.ForeignKey(Patient, blank=True, null=True, on_delete=models.CASCADE, verbose_name='patient_no',
                                   related_name='nurse'
                                   )

    class Meta:
        ordering = ('-last_updated',)

    def __unicode__(self):
        return u'%s' % self.slug

    def get_absolute_url(self):
        return reverse('nurse_models_detail', args=(self.slug,))


    def get_update_url(self):
        return reverse('nurse_models_update', args=(self.slug,))

labs/forms.py
from django import forms
from .models import Labs, Radiology
from .models import RadiologyResult, LabResults

class labsForm(forms.ModelForm):
    class Meta:
        model = Labs
        fields = ['triage_id','lab_name', 'h01', 'h02', 'h03', 'h04', 'h05', 'h06', 'h07', 'h08', 'h09', 'c01', 'c02', 'p01', 'p02', 'p03', 'p04', 'p05', 'p06', 'mbs01', 'mbs02', 'mbs03', 'ge01', 'lks01', 'lks02', 'lks03', 'lks04', 'lks05', 'lks06', 'lks07', 'gm01', 'gm02', 'gm03', 'lm01', 'lm02', 'lm03', 'lm04', 'lpg01', 'lpg02', 'lpg03', 'lpg04', 'lpg05', 'lpg06', 'lpg06', 'lpg07', 'lpg08', 'hv01', 'hv02', 'hv03', 'i01', 'i02', 'i03', 'm01', 'm02', 'm03', 'M04', 'm05', 'm06', 'm07', 'm08', 'g01', 'other', 'diagnosis', 'h01_alergy', 'h02_alergy', 'h03_alergy', 'h04_alergy', 'h06_alergy', 'h07_alergy', 'h08_alergy', 'c01_iron_studies', 'c01_cardiac_markers', 'c02_cardiac_markers', 'c02_cardiac_markers_1', 'lks01_antenatal_screen', 'lks02_antenatal_screen', 'lks04_antenatal_screen', 'lks05_antenatal_screen', 'lks06_antenatal_screen', 'lks07_antenatal_screen', 'gm01_antenatal_screen', 'fsh_menopausal_screen', 'oestradiol_menopausal_screen', 'albumin_menopausal_screen', 'hv02_menopausal_screen', 'hv03_menopausal_screen', 'ast_menopausal_screen', 'i01_menopausal_screen', 'i02_menopausal_screen', 'i03_menopausal_screen', 'patient_no']


class radiologyForm(forms.ModelForm):
    class Meta:
        model = Radiology
        fields = ['triage_id','lpm_date', 'could_b_pregrant', 'examination', 'clinical_indication', 'intra_orbital_fb_hist', 'intracranial_clip', 'pacemaker', 'cochlear_implants', 'prosthetic_hrt_valve', 'pregnancy', 'recent_surgery', 'patient_info', 'diabetic_metformin', 'allergic_contrast', 'other_allergies', 'kidney_problems', 'anticoagulant_drugs', 'egfr_result', 'date', 'patient_no']



class RadiologyResultForm(forms.ModelForm):
    class Meta:
        model = RadiologyResult
        fields = ['patient_no', 'results', 'tests_done', 'uploaded_file','triage_id']

        uploaded_file = forms.FileField(label='Select a profile Image')


class LabResultsForm(forms.ModelForm):
    class Meta:
        model = LabResults
        fields = ['patient_no', 'tests_done', 'test_results', 'uploaded_file','triage_id']

labs/templates/labs/labresults_detail.html
{% extends "base.html" %} {% load static %} {% block content %}
<p><a class="btn btn-default" href="{% url 'labresults_list' %}">LabResults Listing</a></p>
<table class="table">
    <tr>
        <td>slug</td>
        <td>{{ object.slug }}</td>
    </tr>
    <tr>
        <td>created</td>
        <td>{{ object.created }}</td>
    </tr>
    <tr>
        <td>last_updated</td>
        <td>{{ object.last_updated }}</td>
    </tr>
    <tr>
        <td>patient_no</td>
        <td>{{ object.patient_no }}</td>
    </tr>
    <tr>
        <td>tests_done</td>
        <td>{{ object.tests_done }}</td>
    </tr>
    <tr>
        <td>test_results</td>
        <td>{{ object.test_results }}</td>
    </tr>
</table>
<a class="btn btn-primary" href="{{object.get_update_url}}">Edit LabResults</a> {% endblock %}

labs/templates/labs/labresults_list.html
{% extends "base.html" %} {% load static %} {% block content %}
<p><a class="btn btn-default" href="{% url 'labresults_list' %}">LabResults Listing</a></p>
<table class="table">
    <tr>
        <td>ID</td>
        <td>Link</td>
        <td>slug</td>
        <td>created</td>
        <td>last_updated</td>
        <td>patient_no</td>
        <td>tests_done</td>
        <td>test_results</td>
    </tr>
    {% for object in object_list %}
    <tr>
        <td>{{object.pk}}</td>
        <td><a href="{{object.get_absolute_url}}">{{object}}</a></td>
        <td>{{ object.slug }}</td>
        <td>{{ object.created }}</td>
        <td>{{ object.last_updated }}</td>
        <td>{{ object.patient_no }}</td>
        <td>{{ object.tests_done }}</td>
        <td>{{ object.test_results }}</td>
    </tr>
</table>
{% endfor %} {% endblock %}

labs/templates/labs/labs_form.html
{% extends "base.html" %} {% load static %} {% load crispy_forms_tags %} {% block content %}
<script>
    $("#labs_tab").addClass("current").siblings().removeClass("current")
</script>
<p><a class="btn btn-default" href="{% url 'labs_labs_list' %}">labs Listing</a></p>
<form method="post">
    {% csrf_token %} {{form|crispy}}
    <button class="btn btn-primary" type="submit">Submit</button>
</form>
{% endblock %}

labs/templates/labs/labs_list.html
{% extends "base.html" %} {% load static %} {% block content %}
<script>
    $("#labs_tab").addClass("current").siblings().removeClass("current")
</script>


{% endblock %}

labs/templates/labs/radiology_list.html
{% extends "base.html" %} {% load static %} {% block content %}
<script>
    $("#radiology_tab").addClass("current").siblings().removeClass("current")
</script>
<table class="table">

</table>
{% endblock %}

labs/templates/labs/radiology_result_form.html
{% extends "base.html" %} {% load static %} {% load crispy_forms_tags %} {% block content %}
<script>
    $("#radiology_tab").addClass("current").siblings().removeClass("current")
</script>
<style>
    .special {
        padding: 10px;
    }
</style>

<div class="table">

    <div class="mdl-grid">
        <div class="special">Date Requested</div>
        <div class="special">{{ patient.last_updated }}</div>
    </div>

</div>


{% for field in request_ %} {% if field.data %}
<script>
    $(function() {
        $('#id_{{ field.name }}').prop('checked', true)
        console.log("#id_{{ field.name }}")

    })
</script>
{% else %}
<script>
    $(function() {
        $('#div_id_{{ field.name }}').addClass('hidden')
        console.log('#div_id_{{ field.name }}')

    })
</script>

{% endif %} {% endfor %}

<fieldset disabled>
    <div id="radiology_request">
        <div class="mdl-grid ">
            <div id="div_id_patient_no" class="mdl-textfield mdl-js-textfield mdl-textfield--floating-label mdl-cell mdl-cell--12-col">
                <label for="id_patient_no" class="mdl-textfield__label mdl-color-text--black">
                        Patient No</label>
                <div class="controls"><input class="mdl-textfield__input" name="patient_no" id="patient_no" type="text" value="{% if patient.patient_no != None %}{{ patient.patient_no }}{% endif %}" readonly/></div>
            </div>

        </div>
        <div class="mdl-grid">
            <div class="mdl-textfield mdl-js-textfield getmdl-select mdl-cell mdl-cell--12-col">
                <input class="mdl-textfield__input" value="" id="could_b_pregrant" readonly/>
                <input value="" type="hidden" name="could_b_pregrant" />
                <i class="mdl-icon-toggle__label material-icons">keyboard_arrow_down</i>
                <label class="mdl-textfield__label" for="could_b_pregrant">Could you be pregnant</label>
                <ul class="mdl-menu mdl-menu--bottom-left mdl-js-menu" for="could_b_pregrant">
                    <li class="mdl-menu__item" data-val="yes">Yes</li>
                    <li class="mdl-menu__item" data-val="no">No</li>

                </ul>
            </div>
        </div>


        <div class="mdl-grid">
            <div id="div_id_could_b_pregrant" class="mdl-textfield mdl-js-textfield mdl-textfield--floating-label mdl-cell mdl-cell--12-col">
                <label for="id_examination" class="mdl-textfield__label mdl-color-text--grey ">
                        Examination Required
                    </label>
                <div class="controls"><textarea class="mdl-textfield__input" cols="80" id="id_examination" maxlength="20" name="examination" rows="10">{{ examination }}</textarea></div>
            </div>
        </div>

        <div class="mdl-grid">
            <div id="div_id_could_b_pregrant" class="mdl-textfield mdl-js-textfield mdl-textfield--floating-label mdl-cell mdl-cell--12-col">
                <label for="id_clinical_indication" class="mdl-textfield__label mdl-color-text--grey ">
                        Clinical Indications
                    </label>
                <div class="controls"><textarea class="mdl-textfield__input" cols="80" id="id_clinical_indication" maxlength="100" name="clinical_indication" rows="10">{{ clinical_indication }}</textarea></div>
            </div>
        </div>
        <div id="div_id_intra_orbital_fb_hist" class="mdl-cell mdl-cell--12-col">
            <div class="controls"><label for="id_intra_orbital_fb_hist" class="checkbox "> <input
                        class="checkboxinput" id="id_intra_orbital_fb_hist" name="intra_orbital_fb_hist"
                        type="checkbox">
                    Intra orbital fb hist
                </label></div>
        </div>
        <div id="div_id_intracranial_clip" class="mdl-cell mdl-cell--4-col">
            <div class="controls"><label for="id_intracranial_clip" class="checkbox "> <input
                        class="checkboxinput" id="id_intracranial_clip" name="intracranial_clip"
                        type="checkbox">
                    Intracranial clip
                </label></div>
        </div>
        <div id="div_id_pacemaker" class="mdl-cell mdl-cell--4-col">
            <div class="controls"><label for="id_pacemaker" class="checkbox "> <input
                        class="checkboxinput" id="id_pacemaker" name="pacemaker" type="checkbox">
                    Pacemaker
                </label></div>
        </div>
        <div id="div_id_cochlear_implants" class="mdl-cell mdl-cell--4-col">
            <div class="controls"><label for="id_cochlear_implants" class="checkbox "> <input
                        class="checkboxinput" id="id_cochlear_implants" name="cochlear_implants"
                        type="checkbox">
                    Cochlear implants
                </label></div>
        </div>
        <div id="div_id_prosthetic_hrt_valve" class="mdl-cell mdl-cell--4-col">
            <div class="controls"><label for="id_prosthetic_hrt_valve" class="checkbox "> <input
                        class="checkboxinput" id="id_prosthetic_hrt_valve" name="prosthetic_hrt_valve"
                        type="checkbox">
                    Prosthetic hrt valve
                </label></div>
        </div>
        <div id="div_id_pregnancy" class="mdl-cell mdl-cell--4-col">
            <div class="controls"><label for="id_pregnancy" class="checkbox "> <input
                        class="checkboxinput" id="id_pregnancy" name="pregnancy" type="checkbox">
                    Pregnancy
                </label></div>
        </div>
        <div id="div_id_recent_surgery" class="mdl-cell mdl-cell--4-col">
            <div class="controls"><label for="id_recent_surgery" class="checkbox "> <input
                        class="checkboxinput" id="id_recent_surgery" name="recent_surgery"
                        type="checkbox">
                    Recent surgery
                </label></div>
        </div>
        <div id="div_id_patient_info" class="mdl-cell mdl-cell--4-col">
            <div class="controls"><label for="id_patient_info" class="checkbox "> <input
                        class="checkboxinput" id="id_patient_info" name="patient_info" type="checkbox">
                    Patient info
                </label></div>
        </div>
        <div id="div_id_diabetic_metformin" class="mdl-cell mdl-cell--4-col">
            <div class="controls"><label for="id_diabetic_metformin" class="checkbox "> <input
                        class="checkboxinput" id="id_diabetic_metformin" name="diabetic_metformin"
                        type="checkbox">
                    Diabetic metformin
                </label></div>
        </div>
        <div id="div_id_allergic_contrast" class="mdl-cell mdl-cell--4-col">
            <div class="controls"><label for="id_allergic_contrast" class="checkbox "> <input
                        class="checkboxinput" id="id_allergic_contrast" name="allergic_contrast"
                        type="checkbox">
                    Allergic contrast
                </label></div>
        </div>
        <div id="div_id_other_allergies" class="mdl-cell mdl-cell--4-col">
            <div class="controls"><label for="id_other_allergies" class="checkbox "> <input
                        class="checkboxinput" id="id_other_allergies" name="other_allergies"
                        type="checkbox">
                    Other allergies
                </label></div>
        </div>
        <div id="div_id_kidney_problems" class="mdl-cell mdl-cell--4-col">
            <div class="controls"><label for="id_kidney_problems" class="checkbox "> <input
                        class="checkboxinput" id="id_kidney_problems" name="kidney_problems"
                        type="checkbox">
                    Kidney problems
                </label></div>
        </div>
        <div id="div_id_anticoagulant_drugs" class="mdl-cell mdl-cell--4-col">
            <div class="controls"><label for="id_anticoagulant_drugs" class="checkbox "> <input
                        class="checkboxinput" id="id_anticoagulant_drugs" name="anticoagulant_drugs"
                        type="checkbox">
                    Anticoagulant drugs
                </label></div>
        </div>
        <div id="div_id_egfr_result" class="mdl-textfield mdl-js-textfield mdl-textfield--floating-label mdl-cell mdl-cell--4-col"><label for="id_egfr_result" class="mdl-textfield__label mdl-color-text--grey ">
                EGFR result
            </label>
            <div class="controls"><input class="mdl-textfield__input" id="id_egfr_result" maxlength="30" value="
                                                     {% if patient.egfr_result != None %}{{ patient.egfr_result }}{% endif %}" name="egfr_result" type="text"></div>
        </div>

        <div id="div_id_date" class="mdl-textfield mdl-js-textfield mdl-textfield--floating-label mdl-cell mdl-cell--4-col"><label for="id_date" class="mdl-textfield__label mdl-color-text--grey ">
                Date
            </label>
            <div class="controls"><input class="mdl-textfield__input" id="id_date" name="egfr_result" type="date">
            </div>
        </div>
    </div>
</fieldset>
<div class="mdl-cell--9-col" style="margin-top: 20px;">
<form method="post" enctype="multipart/form-data">
    {% csrf_token %}

    <input id="triage_id" type="text" class="hidden" name="triage_id" value=" {{ patient.session_id }}">

    <div class="mdl-grid ">

        <div id="div_id_patient_no" class="mdl-textfield mdl-js-textfield mdl-textfield--floating-label mdl-cell mdl-cell--4-col"><label for="id_patient_no" class="mdl-textfield__label mdl-color-text--black">
                Patient id</label>
            <div class="controls"><input class="mdl-textfield__input" cols="40" id="id_patient_no" maxlength="100" name="patient_no" value="{% if patient.patient_no != None %}{{ patient.patient_no }}{% endif %}" rows="10" readonly></div>
        </div>
    </div>

    <div class="mdl-grid ">
        <div id="div_id_results" class="mdl-textfield mdl-js-textfield mdl-textfield--floating-label mdl-cell mdl-cell--6-col"><label for="id_results" class="mdl-textfield__label mdl-color-text--grey">
                Test results </label>
            <div class="controls"><textarea class="mdl-textfield__input" cols="40" id="id_results" maxlength="400" name="results" rows="10" required="">{% if form.results.value != None %}
                    {{ form.results.value }}{% endif %}</textarea></div>
        </div>

    </div>
    <div class="mdl-grid"><input name="uploaded_file" type="file" /></div>
    <div class="mdl-grid">
        <button name="radiology_btn" class="mdl-button mdl-js-ripple-effect mdl-js-button mdl-button--raised mdl-button--colored mdl-color--primary" type="submit">Submit
            </button>
    </div>

</form>
</div>
{% endblock %}

labs/templates/labs/radiologyresult_detail.html
{% extends "base.html" %} {% load static %} {% block content %}
<script>
    $("#radiology_tab").addClass("current").siblings().removeClass("current")
</script>
<p><a class="btn btn-default" href="{% url 'radiologyresult_list' %}">RadiologyResult Listing</a></p>
<table class="table">
    <tr>
        <td>slug</td>
        <td>{{ object.slug }}</td>
    </tr>
    <tr>
        <td>created</td>
        <td>{{ object.created }}</td>
    </tr>
    <tr>
        <td>last_updated</td>
        <td>{{ object.last_updated }}</td>
    </tr>
    <tr>
        <td>patient_no</td>
        <td>{{ object.patient_no }}</td>
    </tr>
    <tr>
        <td>results</td>
        <td>{{ object.results }}</td>
    </tr>
    <tr>
        <td>tests_done</td>
        <td>{{ object.tests_done }}</td>
    </tr>
</table>
<a class="btn btn-primary" href="{{object.get_update_url}}">Edit RadiologyResult</a> {% endblock %}

labs/templates/labs/radiologyresult_list.html
{% extends "base.html" %} {% load static %} {% block content %}
<script>
    $("#radiology_tab").addClass("current").siblings().removeClass("current")
</script>

<p><a class="btn btn-default" href="{% url 'radiologyresult_list' %}">RadiologyResult Listing</a></p>
<table class="table">
    <tr>
        <td>ID</td>
        <td>Link</td>
        <td>slug</td>
        <td>created</td>
        <td>last_updated</td>
        <td>patient_no</td>
        <td>results</td>
        <td>tests_done</td>
    </tr>
    {% for object in object_list %}
    <tr>
        <td>{{object.pk}}</td>
        <td><a href="{{object.get_absolute_url}}">{{object}}</a></td>
        <td>{{ object.slug }}</td>
        <td>{{ object.created }}</td>
        <td>{{ object.last_updated }}</td>
        <td>{{ object.patient_no }}</td>
        <td>{{ object.results }}</td>
        <td>{{ object.tests_done }}</td>
    </tr>
    {% endfor %}
</table><a class="btn btn-primary" href="{% url 'radiologyresult_create' %}">Create new RadiologyResult</a> {% endblock %}